// <auto-generated />
using System;
using Finanzas.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finanzas.Infrastructure.Migrations
{
    [DbContext(typeof(FinanzasDbContext))]
    [Migration("20261008191001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Finanzas.Domain.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Month", "CategoryId")
                        .IsUnique();

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("Finanzas.Domain.CardCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ClosingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId", "DueDate")
                        .IsUnique();

                    b.ToTable("CardCycles");
                });

            modelBuilder.Entity("Finanzas.Domain.CashBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ObservedBalance")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ObservedDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpeningBalance")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("OpeningDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Scope")
                        .IsUnique();

                    b.ToTable("CashBoxes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Caja familiar consolidada",
                            OpeningBalance = -14346400L,
                            OpeningDate = new DateOnly(2026, 10, 1),
                            Scope = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Memey Mercado Pago",
                            OpeningBalance = 0L,
                            OpeningDate = new DateOnly(2026, 10, 1),
                            Scope = 2
                        });
                });

            modelBuilder.Entity("Finanzas.Domain.CashImpact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CashBoxId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ImpactDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImpactDate");

                    b.HasIndex("TransactionId");

                    b.ToTable("CashImpacts");
                });

            modelBuilder.Entity("Finanzas.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Finanzas.Domain.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CashBoxId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OpeningCardDebt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CashBoxId = 1,
                            Name = "Débito / transferencia",
                            OpeningCardDebt = 0L,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CashBoxId = 1,
                            Name = "Efectivo",
                            OpeningCardDebt = 0L,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            CashBoxId = 2,
                            Name = "Memey Mercado Pago",
                            OpeningCardDebt = 0L,
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            CashBoxId = 1,
                            Name = "Visa Santander",
                            OpeningCardDebt = 0L,
                            Type = 4
                        },
                        new
                        {
                            Id = 5,
                            CashBoxId = 1,
                            Name = "Visa Galicia",
                            OpeningCardDebt = 0L,
                            Type = 4
                        },
                        new
                        {
                            Id = 6,
                            CashBoxId = 1,
                            Name = "Master Galicia",
                            OpeningCardDebt = 0L,
                            Type = 4
                        },
                        new
                        {
                            Id = 7,
                            CashBoxId = 1,
                            Name = "Tarjeta Mercado Pago",
                            OpeningCardDebt = 0L,
                            Type = 4
                        });
                });

            modelBuilder.Entity("Finanzas.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pablo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rocío"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Familia"
                        });
                });

            modelBuilder.Entity("Finanzas.Domain.RecurringRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndMonth")
                        .HasColumnType("TEXT");

                    b.Property<int>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartMonth")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecurringRules");
                });

            modelBuilder.Entity("Finanzas.Domain.RecurringRuleAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FromMonth")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecurringRuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecurringRuleId");

                    b.ToTable("RecurringRuleAmounts");
                });

            modelBuilder.Entity("Finanzas.Domain.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertAttentionPct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertControlPct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertCriticalPct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertExceededPct")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CashFloor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SavingsGoal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlertAttentionPct = 70,
                            AlertControlPct = 80,
                            AlertCriticalPct = 120,
                            AlertExceededPct = 100,
                            CashFloor = 30000000L,
                            SavingsGoal = 50000000L
                        });
                });

            modelBuilder.Entity("Finanzas.Domain.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ConfirmedAmount")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId", "DueDate")
                        .IsUnique();

                    b.ToTable("Statements");
                });

            modelBuilder.Entity("Finanzas.Domain.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FirstDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Installments")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPriorCommitment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaidCardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecurringRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ImportId")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Finanzas.Domain.CardCycle", b =>
                {
                    b.HasOne("Finanzas.Domain.PaymentMethod", null)
                        .WithMany("Cycles")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Finanzas.Domain.CashImpact", b =>
                {
                    b.HasOne("Finanzas.Domain.Transaction", null)
                        .WithMany("Impacts")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Finanzas.Domain.RecurringRuleAmount", b =>
                {
                    b.HasOne("Finanzas.Domain.RecurringRule", null)
                        .WithMany("Amounts")
                        .HasForeignKey("RecurringRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Finanzas.Domain.PaymentMethod", b =>
                {
                    b.Navigation("Cycles");
                });

            modelBuilder.Entity("Finanzas.Domain.RecurringRule", b =>
                {
                    b.Navigation("Amounts");
                });

            modelBuilder.Entity("Finanzas.Domain.Transaction", b =>
                {
                    b.Navigation("Impacts");
                });
#pragma warning restore 612, 618
        }
    }
}
